# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

sudo: required

services:
  - docker

os:
  - linux

julia:
  - 0.4
  - release

notifications:
  email: false

before_success:
    - git clone --depth=50 --branch=master https://github.com/netoelgrande/LLRBTrees.jl.git netoelgrande/LLRBTrees.jl

after_success:
    - julia -e 'cd(Pkg.dir("LLRBTrees")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone("https://github.com/netoelgrande/LLRBTrees.jl.git netoelgrande/LLRBTrees.jl"); Pkg.build("LLRBTrees"); using LLRBTrees'
 - julia -e 'Pkg.clone(pwd()); Pkg.build("LLRBVisualize"); Pkg.test("LLRBVisualize"; coverage=true)'
